### ISSUE TITLE
Missing equivalents

### ISSUE THREAD

**Issue by shakna-israel** [shakna-israel/f.lua#45]
[Lume](https://github.com/rxi/lume) is getting a little popular, and though we cover a lot Lume doesn't, they also have quite a few functions f.lua might benefit from.

**Comment by shakna-israel** [comment]
Possible things to add:

- Math
- [x] clamp (#47)
- [x] round (#48)
- [x] positive? (#49)
- [x] random_choice (#50)
- [x] weighted_random_choice (#50)

- Functional Essentials
- [x] The inverse of cons. e.g. ```sonc({1, 2, 3}, {1, 2, 3, 4, 5}) = {4, 5}``` (#51)
- [x] Shuffle list (#52)
- [x] Sort list (#53)
- [x] Set(array) (#54)
- [x] Swap keys and values (#55)
- [x] memoize (#56)

- Convenience
- [x] Timer (#27)
